### ISSUE TITLE
 suspense is experimental :-)

### ISSUE THREAD

**Issue by MarcWeber** [rakkasjs/preact-on-client#1]
https://preactjs.com/guide/v10/switching-to-preact/

**Comment by cyco130** [comment]
So is Rakkas. From the readme:

> Rakkas is still under heavy development. It uses experimental and/or beta features of React and Vite. Minor releases will introduce breaking changes until we hit 1.0. As such, it's not yet ready for production use.

So I don't really get your point. Feel free to reopen with a better description of the problem you want help with.
